version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: chinoles-mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - chinoles-network

volumes:
  mysql_data:

networks:
  chinoles-network:
    driver: bridge

